Preliminary work to make local debugging of jekyll work.
google/pytype pull request #1239
Opened 2022-06-25 02:35 UTC by byoshimi-github

Running jekyll locally requires a Gemfile and null '---' header to convert .md files to .html (otherwise jekyll doesn't touch these files.)

Also added google_analytics to _config.yml.  Both _layout/*.md files appear to support this already.

2022-06-25 04:09 UTC, byoshimi-github commented
Gemfile cleaned up.  .md references resolve correctly now.   Added `bundle install`.  You should be able to test this locally now using instructions in `debug_docs.md`

2022-06-27 19:57 UTC, rchen152 requested changes

2022-06-27 19:57 UTC, rchen152 commented on docs/developers/index.md
> +---
Are the changes to this file and to index.md below necessary?

2022-06-27 19:57 UTC, rchen152 commented on docs/Gemfile
> +
nit: Could you remove the extra newlines at the end of Gemfile, _config.yml, and debug_docs.md?

2022-06-27 21:15 UTC, byoshimi-github commented
Done.

On Mon, Jun 27, 2022 at 12:57 PM Rebecca Chen ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In docs/developers/index.md
> <https://github.com/google/pytype/pull/1239#discussion_r907746838>:
>
> > @@ -1,3 +1,5 @@
> +---
>
> Are the changes to this file and to index.md below necessary?
> ------------------------------
>
> In docs/Gemfile
> <https://github.com/google/pytype/pull/1239#discussion_r907747612>:
>
> > @@ -0,0 +1,6 @@
> +# frozen_string_literal: true
> +source "https://rubygems.org"
> +
> +gem "webrick"
> +gem "github-pages", "~> 226", group: :jekyll_plugins
> +
>
> nit: Could you remove the extra newlines at the end of Gemfile,
> _config.yml, and debug_docs.md?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/google/pytype/pull/1239#pullrequestreview-1020708440>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUN2NMNOFQB5A5626FMEFTDVRIBSHANCNFSM5ZZQCLJQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-06-27 21:36 UTC, rchen152 approved these changes
Thanks, I'll merge once the checks finish running.

2022-06-28 00:03 UTC, closed without merging